fix: Reloader for docs serve
docs serve --reload crashes otherwise with

TypeError: 'str' object does not support item assignment on
_args[1]['worker_id']